version: "3.8"
services:
  app:
    image: nvmodels:01
    container_name: nvmodels
    # runtime: nvidia
    # command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        - DEV_nvmodels=1
    environment:
    #- AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #- AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - NVIDIA_VISIBLE_DEVICES=all
    - HOME=/app
    - DATA_ROOT=/app/data
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - /home/andreas/data:/app/data